const express=require('express')
const connectDB=require('./config/connectDB')
const cors=require('cors')
require ('dotenv').config()
const app=express()
const PORT=process.env.PORT
app.listen(PORT,(err)=>err?console.log(err):console.log(`App listening on ${PORT}`))
connectDB()
app.use(cors())
app.use(express.json())
app.use('/userAPI',require('./routes/userRoutes'))
app.use('/projectAPI',require('./routes/projectroutes'))